object FrmPrincipal: TFrmPrincipal
  Left = 0
  Top = 0
  BorderStyle = bsDialog
  ClientHeight = 702
  ClientWidth = 741
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  Position = poMainFormCenter
  Scaled = False
  OnCreate = FormCreate
  PixelsPerInch = 96
  TextHeight = 13
  object lblEnviar: TLabel
    Left = 14
    Top = 58
    Width = 46
    Height = 21
    Caption = 'Enviar'
    FocusControl = mmoEnviar
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -17
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
  end
  object lblReceber: TLabel
    Left = 14
    Top = 370
    Width = 61
    Height = 21
    Caption = 'Receber'
    FocusControl = mmoReceber
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -17
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
  end
  object lblQtdLinhas: TLabel
    Left = 14
    Top = 615
    Width = 5
    Height = 21
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -17
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
  end
  object mmoEnviar: TMemo
    Left = 14
    Top = 85
    Width = 713
    Height = 212
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -17
    Font.Name = 'Tahoma'
    Font.Style = []
    HideSelection = False
    ParentFont = False
    ScrollBars = ssVertical
    TabOrder = 0
    OnChange = mmoEnviarChange
  end
  object mmoReceber: TMemo
    Left = 14
    Top = 397
    Width = 713
    Height = 212
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -17
    Font.Name = 'Tahoma'
    Font.Style = []
    HideSelection = False
    ParentFont = False
    ReadOnly = True
    ScrollBars = ssVertical
    TabOrder = 1
    OnChange = mmoReceberChange
  end
  object AdvPanel1: TAdvPanel
    Left = 0
    Top = 0
    Width = 741
    Height = 41
    Align = alTop
    Color = 12615680
    TabOrder = 2
    UseDockManager = True
    Version = '2.5.4.1'
    Caption.Color = clHighlight
    Caption.ColorTo = clNone
    Caption.Font.Charset = DEFAULT_CHARSET
    Caption.Font.Color = clWindowText
    Caption.Font.Height = -11
    Caption.Font.Name = 'Tahoma'
    Caption.Font.Style = []
    Caption.Indent = 0
    DoubleBuffered = True
    StatusBar.Font.Charset = DEFAULT_CHARSET
    StatusBar.Font.Color = clWindowText
    StatusBar.Font.Height = -11
    StatusBar.Font.Name = 'Tahoma'
    StatusBar.Font.Style = []
    Text = ''
    ExplicitWidth = 1479
    FullHeight = 200
    object Label1: TLabel
      Left = 14
      Top = 12
      Width = 72
      Height = 19
      Caption = 'DESAFIO'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -17
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
    end
  end
  object btnEnviar: TButton
    Left = 261
    Top = 303
    Width = 200
    Height = 40
    Caption = 'Enviar'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -17
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    TabOrder = 3
    OnClick = btnEnviarClick
  end
  object btnCopiar: TButton
    Left = 161
    Top = 615
    Width = 200
    Height = 40
    Caption = 'Copiar'
    Enabled = False
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -17
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    TabOrder = 4
    OnClick = btnCopiarClick
  end
  object btnAbrirArquivo: TButton
    Left = 55
    Top = 303
    Width = 200
    Height = 40
    Caption = 'Abrir Arquivo (.txt)'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -17
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    TabOrder = 5
    OnClick = btnAbrirArquivoClick
  end
  object btnLimparReceber: TButton
    Left = 367
    Top = 615
    Width = 200
    Height = 40
    Caption = 'Limpar'
    Enabled = False
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -17
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    TabOrder = 6
    OnClick = btnLimparReceberClick
  end
  object btnLimparEnviar: TButton
    Left = 466
    Top = 303
    Width = 200
    Height = 40
    Caption = 'Limpar'
    Enabled = False
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -17
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    TabOrder = 7
    OnClick = btnLimparEnviarClick
  end
  object OpenDialog1: TOpenDialog
    Left = 672
    Top = 320
  end
end
